server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Esta línea busca primero el archivo real ($uri), luego la carpeta ($uri/) 
        # y si no existe, solo entonces recurre al index.html
        try_files $uri $uri/ /index.html;
    }

    # Asegurar que los archivos javascript se sirvan con el tipo MIME correcto
    location ~ \.js$ {
        root /usr/share/nginx/html;
        types { text/javascript js; }
        default_type text/javascript;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
